<?php


namespace TRAW\EventNotifications\Notifications;


use TRAW\EventDispatch\Events\AbstractEvent;
use TRAW\EventNotifications\Domain\Model\Notification;

/**
 * Class EmailNotification
 * @package TRAW\EventNotifications\Notifications
 */
class EmailNotification extends DefaultNotification
{
    /**
     * @param AbstractEvent $event
     * @param Notification  $notification
     *
     * @return void
     */
    public function sendNotification(AbstractEvent $event, Notification $notification)
    {
        parent::sendNotification($event, $notification); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $message
     *
     * @return string
     */
    public function formatMessageForNotificationType(array $message): string
    {
        return parent::formatMessageForNotificationType($message); // TODO: Change the autogenerated stub
    }
}